openapi: 3.1.0
info:
  title: Notifications
  version: "1.0.0"
paths:
  # Incoming
  /subscription/create:
    $ref: "notifications/operations/incoming.yml#/paths/create"

servers:
  - url: https://api.tatum.io/