info:
  title: RPC
  version: 1.0.0
openapi: 3.1.0
paths:
  /eth_accounts/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_accounts/{apiKey}
  /eth_blockNumber/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_blockNumber/{apiKey}
  /eth_call/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_call/{apiKey}
  /eth_chainId/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_chainId/{apiKey}
  /eth_createAccessList/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_createAccessList/{apiKey}
  /eth_estimateGas/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_estimateGas/{apiKey}
  /eth_feeHistory/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_feeHistory/{apiKey}
  /eth_gasPrice/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_gasPrice/{apiKey}
  /eth_getBalance/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getBalance/{apiKey}
  /eth_getBlockByHash/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getBlockByHash/{apiKey}
  /eth_getBlockByNumber/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getBlockByNumber/{apiKey}
  /eth_getBlockReceipts/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getBlockReceipts/{apiKey}
  /eth_getBlockTransactionCountByHash/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getBlockTransactionCountByHash/{apiKey}
  /eth_getBlockTransactionCountByNumber/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getBlockTransactionCountByNumber/{apiKey}
  /eth_getCode/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getCode/{apiKey}
  /eth_getFilterChanges/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getFilterChanges/{apiKey}
  /eth_getFilterLogs/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getFilterLogs/{apiKey}
  /eth_getLogs/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getLogs/{apiKey}
  /eth_getProof/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getProof/{apiKey}
  /eth_getStorageAt/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getStorageAt/{apiKey}
  /eth_getTransactionByBlockHashAndIndex/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getTransactionByBlockHashAndIndex/{apiKey}
  /eth_getTransactionByBlockNumberAndIndex/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getTransactionByBlockNumberAndIndex/{apiKey}
  /eth_getTransactionByHash/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getTransactionByHash/{apiKey}
  /eth_getTransactionCount/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getTransactionCount/{apiKey}
  /eth_getTransactionReceipt/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getTransactionReceipt/{apiKey}
  /eth_getUncleByBlockHashAndIndex/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getUncleByBlockHashAndIndex/{apiKey}
  /eth_getUncleByBlockNumberAndIndex/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getUncleByBlockNumberAndIndex/{apiKey}
  /eth_getUncleCountByBlockHash/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getUncleCountByBlockHash/{apiKey}
  /eth_getUncleCountByBlockNumber/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_getUncleCountByBlockNumber/{apiKey}
  /eth_maxPriorityFeePerGas/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_maxPriorityFeePerGas/{apiKey}
  /eth_newBlockFilter/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_newBlockFilter/{apiKey}
  /eth_newFilter/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_newFilter/{apiKey}
  /eth_newPendingTransactionFilter/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_newPendingTransactionFilter/{apiKey}
  /eth_protocolVersion/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_protocolVersion/{apiKey}
  /eth_sendPrivateTransaction/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_sendPrivateTransaction/{apiKey}
  /eth_sendRawTransaction/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_sendRawTransaction/{apiKey}
  /eth_uninstallFilter/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/eth_uninstallFilter/{apiKey}
  /genesis:
    $ref: rpc/operations/algorand/algorand.yml#/paths/genesis
  /health:
    $ref: rpc/operations/algorand/algorand.yml#/paths/health
  /metrics:
    $ref: rpc/operations/algorand/algorand.yml#/paths/metrics
  /net_listening/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/net_listening/{apiKey}
  /net_version/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/net_version/{apiKey}
  /ready:
    $ref: rpc/operations/algorand/algorand.yml#/paths/ready
  /swagger.json:
    $ref: rpc/operations/algorand/algorand.yml#/paths/swagger.json
  /v2/accounts:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts
  /v2/accounts/{account-id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{account-id}
  /v2/accounts/{account-id}/apps-local-state:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{account-id}/apps-local-state
  /v2/accounts/{account-id}/assets:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{account-id}/assets
  /v2/accounts/{account-id}/created-applications:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{account-id}/created-applications
  /v2/accounts/{account-id}/created-assets:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{account-id}/created-assets
  /v2/accounts/{account-id}/transactions:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{account-id}/transactions
  /v2/accounts/{address}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{address}
  /v2/accounts/{address}/applications/{application-id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{address}/applications/{application-id}
  /v2/accounts/{address}/assets/{asset-id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{address}/assets/{asset-id}
  /v2/accounts/{address}/transactions/pending:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/accounts/{address}/transactions/pending
  /v2/applications:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/applications
  /v2/applications/{application-id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/applications/{application-id}
  /v2/applications/{application-id}/box:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/applications/{application-id}/box
  /v2/applications/{application-id}/boxes:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/applications/{application-id}/boxes
  /v2/applications/{application-id}/logs:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/applications/{application-id}/logs
  /v2/assets:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/assets
  /v2/assets/{asset-id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/assets/{asset-id}
  /v2/assets/{asset-id}/balances:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/assets/{asset-id}/balances
  /v2/assets/{asset-id}/transactions:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/assets/{asset-id}/transactions
  /v2/blocks/{round-number}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/blocks/{round-number}
  /v2/blocks/{round}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/blocks/{round}
  /v2/blocks/{round}/hash:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/blocks/{round}/hash
  /v2/blocks/{round}/lightheader/proof:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/blocks/{round}/lightheader/proof
  /v2/blocks/{round}/transactions/{txid}/proof:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/blocks/{round}/transactions/{txid}/proof
  /v2/catchup/{catchpoint}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/catchup/{catchpoint}
  /v2/deltas/txn/group/{id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/deltas/txn/group/{id}
  /v2/deltas/{round}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/deltas/{round}
  /v2/deltas/{round}/txn/group:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/deltas/{round}/txn/group
  /v2/devmode/blocks/offset:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/devmode/blocks/offset
  /v2/devmode/blocks/offset/{offset}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/devmode/blocks/offset/{offset}
  /v2/experimental:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/experimental
  /v2/ledger/supply:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/ledger/supply
  /v2/ledger/sync:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/ledger/sync
  /v2/ledger/sync/{round}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/ledger/sync/{round}
  /v2/participation:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/participation
  /v2/participation/{participation-id}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/participation/{participation-id}
  /v2/shutdown:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/shutdown
  /v2/stateproofs/{round}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/stateproofs/{round}
  /v2/status:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/status
  /v2/status/wait-for-block-after/{round}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/status/wait-for-block-after/{round}
  /v2/teal/compile:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/teal/compile
  /v2/teal/disassemble:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/teal/disassemble
  /v2/teal/dryrun:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/teal/dryrun
  /v2/transactions:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/transactions
  /v2/transactions/params:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/transactions/params
  /v2/transactions/pending:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/transactions/pending
  /v2/transactions/pending/{txid}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/transactions/pending/{txid}
  /v2/transactions/simulate:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/transactions/simulate
  /v2/transactions/{txid}:
    $ref: rpc/operations/algorand/algorand.yml#/paths/v2/transactions/{txid}
  /versions:
    $ref: rpc/operations/algorand/algorand.yml#/paths/versions
  /web3_clientVersion/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/web3_clientVersion/{apiKey}
  /web3_sha/{apiKey}:
    $ref: rpc/operations/ethereum/ethereum.yml#/paths/web3_sha/{apiKey}
  accounts:
    $ref: rpc/operations/ethereum/eth.yml#/pathsaccounts
  version:
    $ref: rpc/operations/ethereum/eth.yml#/pathsversion