openapi: 3.1.0
info:
  title: RPC
  version: "1.0.0"
paths:
  # Ethereum
  /eth_accounts/{apiKey}:
    $ref: "rpc/operations/eth.yml#/paths/accounts"
  /eth_version:
    $ref: "rpc/operations/eth.yml#/paths/version"

  # Algorand
  /alg_accounts/{apiKey}:
    $ref: "rpc/operations/alg.yml#/paths/accounts"
  /alg_version:
    $ref: "rpc/operations/alg.yml#/paths/version"
