openapi: 3.1.0
info:
  title: Data API
  version: "1.0.0"
paths:
  # NFT API
  /balances/eth:
    $ref: "data_api/operations/nft.yml#/paths/balances"

  # Token API
  /balances/alg:
    $ref: "data_api/operations/token.yml#/paths/balances"
