openapi: 3.1.0
info:
  title: Data API
  version: "1.0.0"
paths:
  # NFT API
  /v3/data/collections:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1collections"
  /v3/data/metadata:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1metadata"
  /v3/data/owners:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1owners"

  # Token API
  # /v3/data/owners:
  #   $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1owners"
  /v3/data/tokens:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1tokens"

  # Wallet API
  /v3/data/balances:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1balances"
  /v3/data/transactions:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1transactions"
  /v3/data/utxos:
    $ref: "data_api/operations/token.yml#/paths/~1v3~1data~1utxos"
  

  # Transactions API
  /v3/data/transactions:
    $ref: "data_api/operations/transactions.yml#/paths/~1v3~1data~1transactions"
  /v3/data/transactions/hash:
    $ref: "data_api/operations/transactions.yml#/paths/~1v3~1data~1transaction~1hash"

  # DeFi API
  /v3/data/events:
    $ref: "data_api/operations/transactions.yml#/paths/~1v3~1data~1events"