openapi: 3.1.0
info:
  title: Data API
  version: "1.0.1"
paths:
  # Ethereum
  /balances/eth:
    $ref: "data_api/operations/ethereum.yml#/paths/balances"

  # Algorand
  /balances/alg:
    $ref: "data_api/operations/algorand.yml#/paths/balances"
