openapi: 3.1.0
info:
  title: Blockchain Utility
  version: "1.0.0"
paths:
  # VA
  /v3/ledger/account:
    $ref: "blockchain_utility/operations/virtualAccounts.yml#/paths/~1v3~1ledger~1account"

servers:
  - url: https://api.tatum.io/