openapi: 3.1.0
info:
  title: Algorand
  version: 1.0
paths:
  balances:
    post:
      summary: balances
      description: Returns a list of balances.
      tags: ["Algorand"]
      responses:
        200:
          $ref: "../../components/responses.yml#/components/OK"
        400:
          $ref: "../../components/responses.yml#/components/Error400"
      operationId: alg_balances
