components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: t-645a26e22d0761001c811c84-645a26e32d0761001c811c8a
security:
  - ApiKeyAuth: []

info:
  title: Data API
  version: "1.0.0"
openapi: 3.0.3
paths:
  /v3/data/transactions:
    get:
      tags:
        - Transactions API
        - Wallet API
      summary: getTransactions
      operationId: getTransactions
      parameters:
        - name: chain
          in: query
          required: true
          schema:
            type: string
          description: Blockchain to query (e.g., ethereum)
      responses:
        '200':
          description: Successful response
          # Define response schema

  /v3/data/transactions/hash:
    get:
      tags:
        - Transactions API
      summary: Retrieve transaction details by hash
      operationId: getTransactionByHash
      parameters:
        - name: chain
          in: query
          required: true
          schema:
            type: string
          description: Blockchain to query (e.g., ethereum)
        - name: hash
          in: query
          required: true
          schema:
            type: string
          description: Transaction hash
      responses:
        '200':
          description: Successful response
          # Define response schema

servers:
  - url: https://api.tatum.io/
